package com.pawmino.app

import com.pawmino.app.model.ScheduleType
import com.pawmino.app.model.TaskStatus
import com.pawmino.app.model.WeekDay
import com.pawmino.app.util.TaskGenerator
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.LocalDate

class TaskGeneratorTest {

    // 2026-07-10 is a Friday.
    private val friday = LocalDate.of(2026, 7, 10)
    private val fridayIso = "2026-07-10"

    @Test
    fun daily_isAlwaysActive() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily)
        assertTrue(TaskGenerator.isActiveOn(t, friday))
        assertTrue(TaskGenerator.isActiveOn(t, friday.plusDays(1)))
    }

    @Test
    fun disabledTask_isNeverActive() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, enabled = false)
        assertFalse(TaskGenerator.isActiveOn(t, friday))
    }

    @Test
    fun selectedDays_matchesOnlyChosenWeekdays() {
        val t = TestData.task("t", scheduleType = ScheduleType.SelectedDays, daysOfWeek = listOf(WeekDay.Friday))
        assertTrue(TaskGenerator.isActiveOn(t, friday))
        assertFalse(TaskGenerator.isActiveOn(t, friday.plusDays(1))) // Saturday
    }

    @Test
    fun oneTime_matchesOnlySpecificDate() {
        val t = TestData.task("t", scheduleType = ScheduleType.OneTime, specificDate = fridayIso)
        assertTrue(TaskGenerator.isActiveOn(t, friday))
        assertFalse(TaskGenerator.isActiveOn(t, friday.plusDays(1)))
    }

    @Test
    fun everyNumberOfDays_usesAnchorAndInterval() {
        val t = TestData.task(
            "t",
            scheduleType = ScheduleType.EveryNumberOfDays,
            repeatIntervalDays = 3,
            anchorDate = fridayIso
        )
        assertTrue(TaskGenerator.isActiveOn(t, friday))               // day 0
        assertFalse(TaskGenerator.isActiveOn(t, friday.plusDays(1)))  // day 1
        assertTrue(TaskGenerator.isActiveOn(t, friday.plusDays(3)))   // day 3
        assertFalse(TaskGenerator.isActiveOn(t, friday.minusDays(1))) // before anchor
    }

    @Test
    fun everyNumberOfDays_invalidIntervalIsInactive() {
        val t = TestData.task("t", scheduleType = ScheduleType.EveryNumberOfDays, repeatIntervalDays = 0, anchorDate = fridayIso)
        assertFalse(TaskGenerator.isActiveOn(t, friday))
    }

    @Test
    fun unscheduled_isNeverAutoGenerated() {
        val t = TestData.task("t", scheduleType = ScheduleType.Unscheduled)
        assertFalse(TaskGenerator.isActiveOn(t, friday))
    }

    @Test
    fun multipleTimes_generateOneInstanceEach() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, times = listOf("08:00", "18:00"))
        val instances = TaskGenerator.desiredInstances(t, fridayIso, friday)
        assertEquals(2, instances.size)
        assertEquals(listOf("08:00", "18:00"), instances.map { it.scheduledTime }.sorted())
    }

    @Test
    fun noTime_generatesSingleAnytimeInstance() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, times = emptyList())
        val instances = TaskGenerator.desiredInstances(t, fridayIso, friday)
        assertEquals(1, instances.size)
        assertEquals("", instances.first().scheduledTime)
    }

    @Test
    fun ensureInstances_doesNotDuplicate() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, times = listOf("08:00"))
        val (first, added1) = TaskGenerator.ensureInstances(emptyList(), listOf(t), "pet1", fridayIso)
        assertEquals(1, added1.size)
        val (second, added2) = TaskGenerator.ensureInstances(first, listOf(t), "pet1", fridayIso)
        assertEquals(0, added2.size)
        assertEquals(1, second.size)
    }

    @Test
    fun ensureInstances_preservesCompletionHistory() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, times = listOf("08:00"))
        val (first, _) = TaskGenerator.ensureInstances(emptyList(), listOf(t), "pet1", fridayIso)
        val completed = first.map { it.copy(status = TaskStatus.Completed) }
        val (second, added) = TaskGenerator.ensureInstances(completed, listOf(t), "pet1", fridayIso)
        assertEquals(0, added.size)
        assertEquals(TaskStatus.Completed, second.first().status)
    }

    @Test
    fun activeInstancesFor_excludesDeletedTaskReferences() {
        val t = TestData.task("t", scheduleType = ScheduleType.Daily, times = listOf("08:00"))
        val (stored, _) = TaskGenerator.ensureInstances(emptyList(), listOf(t), "pet1", fridayIso)
        // Task list no longer contains the task -> not active.
        val active = TaskGenerator.activeInstancesFor(stored, emptyList(), "pet1", fridayIso)
        assertTrue(active.isEmpty())
    }
}
